[package]
name = "puzzle-1"
version = "0.1.0"
authors = ["Soypete <34897832+Soypete@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
